import type { Metadata } from 'next';
import { Bebas_Neue, Inter, Oswald } from 'next/font/google';
import './globals.css';

import Header from '@/components/Header';

const bebasNeue = Bebas_Neue({
  variable: '--font-bebas-neue',
  subsets: ['latin', 'latin-ext'],
  weight: ['400'],
});

const oswald = Oswald({
  variable: '--font-oswald',
  subsets: ['cyrillic'],
  weight: ['400'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${inter.variable} ${oswald.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
